/* eslint-disable */
// Generated by Wrangler

interface R2Bucket { [key: string]: any; }
interface D1Database { [key: string]: any; }
interface SendEmail { [key: string]: any; }

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env {
		BUCKET: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		VITE_SUPABASE_PROJECT_ID: string;
		VITE_SUPABASE_URL: string;
		VITE_SUPABASE_PUBLISHABLE_KEY: string;
		SUPABASE_URL: string;
		SUPABASE_PUBLISHABLE_KEY: string;
		VITE_GOOGLE_MAPS_API_KEY: string;
		VITE_GOOGLE_CLIENT_ID: string;
		VITE_RAZORPAY_KEY_ID: string;
		RAZORPAY_KEY_SECRET: string;
		RAZORPAY_OFFER_TSRHELP_ID: string;
		JWT_SECRET: string;
		RESEND_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SUPABASE_PROJECT_ID" | "VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "VITE_GOOGLE_MAPS_API_KEY" | "VITE_GOOGLE_CLIENT_ID" | "VITE_RAZORPAY_KEY_ID" | "RAZORPAY_KEY_SECRET" | "RAZORPAY_OFFER_TSRHELP_ID" | "JWT_SECRET" | "RESEND_API_KEY">> {}
}
