/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToursNewRouteImport } from './routes/tours.new'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ToursTourIdIndexRouteImport } from './routes/tours.$tourId.index'
import { Route as ToursTourIdPublishRouteImport } from './routes/tours.$tourId.publish'
import { Route as ToursTourIdLocationRouteImport } from './routes/tours.$tourId.location'
import { Route as ToursTourIdConnectionsRouteImport } from './routes/tours.$tourId.connections'
import { Route as ToursTourIdAnalyticsRouteImport } from './routes/tours.$tourId.analytics'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursNewRoute = ToursNewRouteImport.update({
  id: '/tours/new',
  path: '/tours/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdIndexRoute = ToursTourIdIndexRouteImport.update({
  id: '/tours/$tourId/',
  path: '/tours/$tourId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdPublishRoute = ToursTourIdPublishRouteImport.update({
  id: '/tours/$tourId/publish',
  path: '/tours/$tourId/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdLocationRoute = ToursTourIdLocationRouteImport.update({
  id: '/tours/$tourId/location',
  path: '/tours/$tourId/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdConnectionsRoute = ToursTourIdConnectionsRouteImport.update({
  id: '/tours/$tourId/connections',
  path: '/tours/$tourId/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdAnalyticsRoute = ToursTourIdAnalyticsRouteImport.update({
  id: '/tours/$tourId/analytics',
  path: '/tours/$tourId/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/new': typeof ToursNewRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/tours/$tourId/analytics': typeof ToursTourIdAnalyticsRoute
  '/tours/$tourId/connections': typeof ToursTourIdConnectionsRoute
  '/tours/$tourId/location': typeof ToursTourIdLocationRoute
  '/tours/$tourId/publish': typeof ToursTourIdPublishRoute
  '/tours/$tourId/': typeof ToursTourIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/new': typeof ToursNewRoute
  '/blog': typeof BlogIndexRoute
  '/tours': typeof ToursIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/tours/$tourId/analytics': typeof ToursTourIdAnalyticsRoute
  '/tours/$tourId/connections': typeof ToursTourIdConnectionsRoute
  '/tours/$tourId/location': typeof ToursTourIdLocationRoute
  '/tours/$tourId/publish': typeof ToursTourIdPublishRoute
  '/tours/$tourId': typeof ToursTourIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/new': typeof ToursNewRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/tours/$tourId/analytics': typeof ToursTourIdAnalyticsRoute
  '/tours/$tourId/connections': typeof ToursTourIdConnectionsRoute
  '/tours/$tourId/location': typeof ToursTourIdLocationRoute
  '/tours/$tourId/publish': typeof ToursTourIdPublishRoute
  '/tours/$tourId/': typeof ToursTourIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/tours/new'
    | '/blog/'
    | '/tours/'
    | '/auth/google/callback'
    | '/tours/$tourId/analytics'
    | '/tours/$tourId/connections'
    | '/tours/$tourId/location'
    | '/tours/$tourId/publish'
    | '/tours/$tourId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/tours/new'
    | '/blog'
    | '/tours'
    | '/auth/google/callback'
    | '/tours/$tourId/analytics'
    | '/tours/$tourId/connections'
    | '/tours/$tourId/location'
    | '/tours/$tourId/publish'
    | '/tours/$tourId'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/blog/$slug'
    | '/tours/new'
    | '/blog/'
    | '/tours/'
    | '/auth/google/callback'
    | '/tours/$tourId/analytics'
    | '/tours/$tourId/connections'
    | '/tours/$tourId/location'
    | '/tours/$tourId/publish'
    | '/tours/$tourId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToursNewRoute: typeof ToursNewRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  ToursTourIdAnalyticsRoute: typeof ToursTourIdAnalyticsRoute
  ToursTourIdConnectionsRoute: typeof ToursTourIdConnectionsRoute
  ToursTourIdLocationRoute: typeof ToursTourIdLocationRoute
  ToursTourIdPublishRoute: typeof ToursTourIdPublishRoute
  ToursTourIdIndexRoute: typeof ToursTourIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/new': {
      id: '/tours/new'
      path: '/tours/new'
      fullPath: '/tours/new'
      preLoaderRoute: typeof ToursNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/': {
      id: '/tours/$tourId/'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId/'
      preLoaderRoute: typeof ToursTourIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/publish': {
      id: '/tours/$tourId/publish'
      path: '/tours/$tourId/publish'
      fullPath: '/tours/$tourId/publish'
      preLoaderRoute: typeof ToursTourIdPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/location': {
      id: '/tours/$tourId/location'
      path: '/tours/$tourId/location'
      fullPath: '/tours/$tourId/location'
      preLoaderRoute: typeof ToursTourIdLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/connections': {
      id: '/tours/$tourId/connections'
      path: '/tours/$tourId/connections'
      fullPath: '/tours/$tourId/connections'
      preLoaderRoute: typeof ToursTourIdConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/analytics': {
      id: '/tours/$tourId/analytics'
      path: '/tours/$tourId/analytics'
      fullPath: '/tours/$tourId/analytics'
      preLoaderRoute: typeof ToursTourIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToursNewRoute: ToursNewRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  ToursTourIdAnalyticsRoute: ToursTourIdAnalyticsRoute,
  ToursTourIdConnectionsRoute: ToursTourIdConnectionsRoute,
  ToursTourIdLocationRoute: ToursTourIdLocationRoute,
  ToursTourIdPublishRoute: ToursTourIdPublishRoute,
  ToursTourIdIndexRoute: ToursTourIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
